version: "3.9"
services:
    php:
        build:
            context: .
            dockerfile: php.dockerfile
        container_name: php
        volumes:
            - "./src:/var/www/html"
        ports:
            - 80:80
            # - 443:443
    mysql:
        image: mysql:8.0.30
        platform: linux/amd64
        container_name: mysql
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
    composer:
        image: composer:latest
        container_name: composer
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
    artisan:
        build:
            context: .
            dockerfile: php.dockerfile
        container_name: artisan
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['php', 'artisan']
    npm:
        image: node:current-alpine
        container_name: npm
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['npm']

